### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by btcdrak** [bitcoin-core/bitcoincore.org#29]
This is an open todo list, I'll add more as topics come up.
- [x] nested dropdown navigation
- [x] segwit adoption page (which wallets have adopted/will adopt)
- [x] software life cycle (to communicate release dates, maintenance schedules and EOL [in progress]
- [x] privacy policy
- [x] legal page
- [ ] security page with information on how to responsibly report security vulnerabilities to Bitcoin Core
- [ ] homepage landing page @jonasschnelli 
- [x] show English version when translation is not available
- [x] supported BIPs
- [x] allow users to show support for the project
- [x] ~~add footer of major supporters~~
- [x] add twitter feed
- [x] RSS feed for meetings
- [x] Transifex translation process

**Comment by jakerockland** [comment]
@btcdrak What would be a good way of going about starting the supporters list?

**Comment by btcdrak** [comment]
@jakerockland It's here: https://bitcoincore.org/en/supporters/ and there is a footer in progress in #48, just not integrated.

**Comment by jakerockland** [comment]
ah my mistake @btcdrak, thank you! Looking to see how I can be helpful to the project.

**Comment by MarcoFalke** [comment]
>  security page with information on how to responsibly report security vulnerabilities to Bitcoin Core

This has been done. Can be closed.

**Comment by MarcoFalke** [comment]
There is https://bitcoincore.org/en/contact/ and https://github.com/bitcoin/bitcoin/security
